repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: local
    hooks:
    -   id: django-test
        name: django-test
        entry: python manage.py test
        language: system
        pass_filenames: false
        always_run: true

    -   id: model-validation
        name: model-validation
        entry: python manage.py validate_models
        language: system
        pass_filenames: false
        always_run: true

    -   id: deploy-check
        name: deploy-check
        entry: python deploy_checklist.py
        language: system
        pass_filenames: false
        always_run: true
