[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn coophive.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python39"]
