# Generated by Django 5.2.5 on 2025-08-13 16:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=50)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('published_time', models.DateTimeField(blank=True, null=True)),
                ('platform_post_id', models.CharField(blank=True, max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=20)),
                ('file_url', models.URLField()),
                ('original_filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform_media_ids', models.JSONField(default=dict)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='core.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
