# Generated by Django 5.2.5 on 2025-08-15 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mediaasset',
            options={},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='original_filename',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='platform_media_ids',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='post',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campaign'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mentions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
