# Generated by Django 5.2.5 on 2025-08-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('reply_to_tweet_id', models.CharField(blank=True, max_length=100)),
                ('quoted_tweet_id', models.CharField(blank=True, max_length=100)),
                ('is_thread', models.BooleanField(default=False)),
                ('thread_position', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('quote_tweets', models.IntegerField(default=0)),
                ('bookmarks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Twitter Post',
                'verbose_name_plural': 'Twitter Posts',
            },
            bases=('core.post',),
        ),
    ]
