# Generated by Django 5.2.5 on 2025-08-14 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('secure_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_summary', models.JSONField()),
                ('total_tweets', models.IntegerField()),
                ('ready_for_deployment', models.IntegerField()),
                ('source_type', models.CharField(default='multi_agent_automation', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('brand_alignment_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaign Batch',
                'verbose_name_plural': 'Campaign Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('quotes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='success', max_length=50)),
                ('tweet_url', models.URLField()),
                ('execution_id', models.CharField(max_length=255)),
                ('source_url', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Source Tweet',
                'verbose_name_plural': 'Source Tweets',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='audience_target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='brand_alignment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='coophive_elements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='campaign_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.campaignbatch'),
        ),
        migrations.CreateModel(
            name='GeneratedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('character_count', models.IntegerField()),
                ('engagement_hook', models.TextField()),
                ('coophive_elements', models.JSONField()),
                ('discord_voice_patterns', models.JSONField()),
                ('theme_connection', models.TextField()),
                ('ready_for_deployment', models.BooleanField()),
                ('status', models.CharField(choices=[('Brand Aligned', 'Brand Aligned'), ('Draft', 'Draft'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Rejected', 'Rejected'), ('Deleted', 'Deleted')], default='Brand Aligned', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('x_com_post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter.campaignbatch')),
            ],
            options={
                'verbose_name': 'Generated Tweet',
                'verbose_name_plural': 'Generated Tweets',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='twitterpost',
            name='generated_tweet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twitter.generatedtweet'),
        ),
    ]
