# Generated by Django 5.2.5 on 2025-08-14 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('reset', 'Password Reset'), ('google_verification', 'Google OAuth Verification')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='user_accoun_email_a98dfd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('register_email', 'Register (E-mail)'), ('login_email', 'Login (E-mail)'), ('login_google', 'Login (Google)'), ('logout', 'Logout'), ('verify_code', 'Verification Code'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('register_email_breach', 'Registration Breach (Email)'), ('password_reset_breach', 'Password Reset Breach'), ('google_oauth_breach', 'OAuth Breach (Google)'), ('google_verification_sent', 'Google Verification Code Sent'), ('google_verification_success', 'Google Verification Success')], max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='user_accoun_event_t_21e0fd_idx'), models.Index(fields=['email'], name='user_accoun_email_e0d9b5_idx')],
            },
        ),
    ]
