# Generated by Django 5.2.5 on 2025-08-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarcasterPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('cast_hash', models.CharField(blank=True, max_length=100)),
                ('parent_cast_hash', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('recasts', models.IntegerField(default=0)),
                ('watches', models.IntegerField(default=0)),
                ('reactions', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Farcaster Post',
                'verbose_name_plural': 'Farcaster Posts',
            },
            bases=('core.post',),
        ),
    ]
