# Generated by Django 5.2.5 on 2025-08-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('article_url', models.URLField(blank=True)),
                ('company_page_id', models.CharField(blank=True, max_length=100)),
                ('impressions', models.IntegerField(default=0)),
                ('click_through_rate', models.FloatField(default=0.0)),
                ('engagement_rate', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'LinkedIn Post',
                'verbose_name_plural': 'LinkedIn Posts',
            },
            bases=('core.post',),
        ),
    ]
