# Generated by Django 5.2.5 on 2025-08-15 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsetting',
            options={'ordering': ['key'], 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
