# Generated by Django 5.2.5 on 2025-08-13 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueskyPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.post')),
                ('rkey', models.CharField(blank=True, max_length=100)),
                ('uri', models.CharField(blank=True, max_length=255)),
                ('reply_root', models.CharField(blank=True, max_length=255)),
                ('reply_parent', models.CharField(blank=True, max_length=255)),
                ('reposts', models.IntegerField(default=0)),
                ('self_labels', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Bluesky Post',
                'verbose_name_plural': 'Bluesky Posts',
            },
            bases=('core.post',),
        ),
    ]
